/* Variables header for application - AppBuilder 2.01  */

/* 'base' Window link */
const int ABN_base = 0;
const int ABN_menuFile = 1;
const int ABN_heading = 2;
const int ABN_artHorizon = 3;
const int ABN_positionView = 4;
const int ABN_myTimer = 5;
const int ABN_buttonZoomOut = 6;
const int ABN_buttonClear = 7;
const int ABN_buttonZoomIn = 8;
const int ABN_textPosStat = 9;
const int ABN_valBufferSize = 10;
const int ABN_buttonZero = 11;
const int ABN_uncertainty_group = 12;
const int ABN_valUncZ = 13;
const int ABN_valUncY = 14;
const int ABN_valUncX = 15;
const int ABN_llh_group = 16;
const int ABN_valHeight = 17;
const int ABN_valLat = 18;
const int ABN_valLong = 19;
const int ABN_vel_group = 20;
const int ABN_valVelZ = 21;
const int ABN_valVelY = 22;
const int ABN_valVelX = 23;
const int ABN_ned_group = 24;
const int ABN_valPosX = 25;
const int ABN_valPosY = 26;
const int ABN_valPosZ = 27;
const int ABN_accel_group = 28;
const int ABN_valAccZ = 29;
const int ABN_valAccY = 30;
const int ABN_valAccX = 31;
const int ABN_rpyrate_group = 32;
const int ABN_valYawRate = 33;
const int ABN_valPitchRate = 34;
const int ABN_valRollRate = 35;
const int ABN_rpy_group = 36;
const int ABN_valYaw = 37;
const int ABN_valPitch = 38;
const int ABN_valRoll = 39;
const int ABN_textPosType = 40;
const int ABN_onOffPause = 41;
const int ABN_valZoomX0 = 42;
const int ABN_valZoomX1 = 43;
const int ABN_valZoomX2 = 44;
const int ABN_valZoomX3 = 45;
const int ABN_valZoomX4 = 46;
const int ABN_valZoomX5 = 47;
const int ABN_valZoomX6 = 48;
const int ABN_valZoomX7 = 49;
const int ABN_valZoomX8 = 50;
const int ABN_valZoomY0 = 51;
const int ABN_valZoomY1 = 52;
const int ABN_valZoomY2 = 53;
const int ABN_valZoomY3 = 54;
const int ABN_valZoomY4 = 55;
const int ABN_valZoomY5 = 56;
const int ABN_valZoomY6 = 57;
const int ABN_valZoomY7 = 58;
const int ABN_valZoomY8 = 59;
const int ABN_trendUnc = 60;
const int ABN_textAnnounce = 61;
const int ABN_textErr = 62;

/* 'file_open_dialog' Dialog link */
const int ABN_file_open_dialog = 63;
const int ABN_waypoint_file_group = 64;
const int ABN_waypoint_directory_selector = 65;
const int ABN_waypoint_filename_text = 66;
const int ABN_waypoint_file_cancel_button = 67;
const int ABN_create_waypoint_file_button = 68;

/* 'fileMenu' Menu link */
const int ABN_fileMenu = 69;
const int ABN_fileMenuWaypointFile = 70;
const int ABN_fileMenuCloseWaypointFile = 71;
const int ABN_fileMenuQuit = 72;
const int ABN_fileMenuAddWaypoint = 74;

